### ISSUE TITLE
No Track Scrolling

### ISSUE THREAD

**Issue by NF-Codestuffs** [satchelspencer/repsyps#5]
When I play a track, the waveform does not scroll so I am only ever able to see and interact with the first part of the track. The track still plays past the visible part, but I cannot scroll to see the rest of the track.

**Comment by NF-Codestuffs** [comment]
Also, I do have track scrolling turned on in settings

**Comment by satchelspencer** [comment]
If you're using a trackpad, two finger scrolling left and right should let you scroll forward and backward though the track. If you're using a mouse wheel hold down shift to scroll left and right. As far as automatic scrolling, that's disabled when you're editing the time grid so it could be that you just haven't clicked save under "Time Grid" in the track sidebar. If you're still having problems let me know what os / computer you're using, and i'll look into it further. 

cheers!

**Comment by satchelspencer** [comment]
feel free to reopen if you need, no action for me to take here (:
